% Script file to tidy up the workspace and remove the non needed temporary 
% variables after execution

clear accel_bias accel_bias_std_dev accel_bias_x accel_bias_y accel_bias_z...
       accel_noise_std_dev accel_noise_x accel_noise_y accel_noise_z accel_x accel_y accel_z accel_fb...
       data dt dv_down dv_east dv_north east_pos...
       euler_init GPS_pos_bias_std_dev GPS_pos_noise_std_dev GPS_vel_bias_std_dev GPS_vel_noise_std_dev... 
       GPS_vel_down  GPS_vel_east GPS_vel_north GPS_sampling_rate...
       GPS_down_pos  GPS_east_pos GPS_north_pos GPS_ned_vel ...
       gyro_bias gyro_bias_x gyro_bias_y gyro_bias_z gyro_bias_std_dev gyro_noise_std_dev....
       gyro_noise_x gyro_noise_y gyro_noise_z gyro_wb_x gyro_wb_y gyro_wb_z gyro_wb....
       mag_bias_x mag_bias_y mag_bias_z mag_bias_std_dev mag_noise_std_dev....
       mag_noise_x mag_noise_y mag_noise_z mag_x mag_y mag_z mag_variation mag_orient....
       meas_orient meas_pos meas_vel orient_meas_noise orient_proc_noise orient_rad p_k north_pos...
       P_orient_init pos_init P_vel_init  pitch pos_proc_noise pos_meas_noise vel_proc_noise vel_meas_noise x_k std_dev...
       roll yaw yaw_measurement_rad vel_init i itr m  t n...
       wrap mag estimates orient_error truths plot_names pos1 xdot_A zhat_H down_pos dv_ned est_down_pos est_east_pos est_ned_vel est_north_pos est_pitch est_roll est_yaw...
       mag_to_ned mag_x_y_z ned_to_body ned_vel pitch_rad pos_error roll_rad sensor_ned_vel...  
       vel_error yaw_meas yaw_rad P_pos_init  g animation_speed down_pos east_pos est_down_pos est_east_pos est_north_pos...
       GPS_east_pos GPS_north_pos GPS_down_pos hFig1 hFig2 hFig3 hPlot1 hPlot2 hPlot3 i n north_pos...
       xdata ydata zdata z
   
      
   
